version: '3'

tasks:
  build:
    desc: Build all go packages
    cmds: [go build ./...]

  gen:protobuf:
    desc: Generate protobuf go stubs
    sources:
      - api/**/*.proto
    generates:
      - gen/**/*.go
    cmds:
      - |
        protoc \
        --proto_path={{.ROOT_DIR}}/api \
        --go_out={{.ROOT_DIR}}/gen \
        --go_opt=paths=source_relative \
        --go-grpc_out={{.ROOT_DIR}}/gen \
        --go-grpc_opt=paths=source_relative \
        {{.ROOT_DIR}}/api/**/*.proto

  fmt:
    desc: Format source files
    cmds: [go fmt ./...]
