version: '3'

tasks:
  build:
    desc: Build all go packages
    cmds: [go build ./...]

  gen:
    desc: Generate protobuf implementations
    sources:
      - api/**/*.proto
    generates:
      - gen/**/*.go
    cmds: [buf generate]

  fmt:
    desc: Format source files
    cmds: [go fmt ./...]
